### ISSUE TITLE
How to detect all identical products

### ISSUE THREAD

**Issue by monkeycc** [multi-template-matching/MultiTemplateMatching-Python#23]
![349293-20210403230217832-1802403393](https://github.com/user-attachments/assets/2baf9dfb-df0c-4948-ad65-d31cf5a81bf9)

Discovering rotating objects
The detection effect is not good

**Comment by LauLauThom** [comment]
That's expected, you would need to use multiple templates representing the expected rotations.  
Since your objects can have any orientation multi-template-matching might not be very efficient.
It's explained in the associated publication below :

https://doi.org/10.1186/s12859-020-3363-7

**Comment by monkeycc** [comment]
Thank you for your response
