### ISSUE TITLE
Possible outside Jupyter?

### ISSUE THREAD

**Issue by SB2020-eye** [multi-template-matching/MultiTemplateMatching-Python#5]
Hi. Is it possible to use MTM outside of Jupyter? For example, in Visual Studio Code, using Anaconda/Python3.7 (and not a Jupyter notebook)?

**Comment by LauLauThom** [comment]
Yes of course, like any other python package.
Just install it in your anaconda environment via the anaconda prompt by typing `pip install Multi-Template-Matching` 
Then you can do `import MTM` in Visual studio code, or any other code editor like spyder.

**Comment by SB2020-eye** [comment]
Thank you so much. Yes, I gave this a try. I am very new to python. Would you mind taking a look at the error it returns, below?

```
[Running] python -u "c:\Users\Scott\Desktop\Python2\TestTemplateMatchingM.py"
Traceback (most recent call last):
  File "c:\Users\Scott\Desktop\Python2\TestTemplateMatchingM.py", line 23, in <module>
    Hits = matchTemplates(listTemplate, image, method=cv2.TM_CCOEFF_NORMED, N_object=float("inf"), score_threshold=0.5, maxOverlap=0, searchBox=None)
  File "C:\Users\Scott\anaconda3\lib\site-packages\MTM\__init__.py", line 181, in matchTemplates
    elif method in (3,5): bestHits = NMS(tableHit, N_object=N_object, maxOverlap=maxOverlap, sortAscending=False)
  File "C:\Users\Scott\anaconda3\lib\site-packages\MTM\NMS.py", line 121, in NMS
    threshTable.sort_values("Score", ascending=sortAscending, inplace=True) # Warning here is fine
  File "C:\Users\Scott\anaconda3\lib\site-packages\pandas\core\frame.py", line 4927, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\Scott\anaconda3\lib\site-packages\pandas\core\generic.py", line 1692, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'Score'

[Done] exited with code=1 in 12.797 seconds
```

**Comment by LauLauThom** [comment]
Do you use Python 2 ?  
The package is python 3 only, python 2 is deprecated now.  

Can you attach the script (TestTemplateMatchingM.py) that you are trying to run so I can try to reproduce the issue.  
I would also need an example input image and template.  
You can attach them to your next answer by drag and dropping.

And finally I also need the version of MTM you are using.
You can get it by running `print (MTM.__version__)` with double underscore before and after "version".
Thanks !

**Comment by LauLauThom** [comment]
Wait actually I think you found a bug that arises when no object is found.
I will publish a corrective version in a few, then you can update with pip. I will let you know

**Comment by LauLauThom** [comment]
You can now update to version 1.6.0.post1 by entering `pip install Multi-Template-Matching --upgrade` in a command prompt or anaconda prompt.
This should fix the issue above

**Comment by LauLauThom** [comment]
Glad that it works for you !
Indeed I did not pay attention to that. Basically you can name your list of templates as you like ex: 
`myTemplates=[("A", someNumpyArray)]` 
as long as you give it as first parameter to `matchTemplates` it will work.

Only if you want to explicitly mention the parameters
`matchTemplates(listTemplates=myTemplates)`

**Comment by SB2020-eye** [comment]
Yes. Got it now. Thanks!
