### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by SB2020-eye** [multi-template-matching/MultiTemplateMatching-Python#8]
Hi. Is it possible [this](https://github.com/multi-template-matching/MultiTemplateMatching-Python/blob/74d5e0c2c68e34c79fd46a0de191f19a51a12480/MTM/NMS.py#L40
) is a typo?

    `- sortAscending : use True when low score means better prediction (Difference-based score), True otherwise (Correlation score)`

(Should it say "False otherwise"?)

**Comment by LauLauThom** [comment]
Indeed thanks for spotting it, that's one the few stuff I need to correct before the next release.
Just pushed a commit to the template-mask branch to correct it
